### ISSUE TITLE
Failed to compile with v140.0.0

### ISSUE THREAD

**Issue by linrongbin16** [denoland/rusty_v8#1849]
Hi, I create an example project to build with v8 140.0.0 here: https://github.com/linrongbin16/rusty_v8_example

But I cannot successfully build it, here's the CI job: https://github.com/linrongbin16/rusty_v8_example/actions/runs/17669573518

On my local MacBook M1 chip, `cargo build` failed with below error message:

```
❯ cargo build
   Compiling temporal_rs v0.0.11
error: unexpected end of macro invocation
  --> /Users/rlin/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/temporal_rs-0.0.11/src/tzdb.rs:60:1
   |
60 | timezone_provider::iana_normalizer_singleton!();
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing tokens in macro arguments
   |
note: while trying to match meta-variable `$providername:ident`
  --> /Users/rlin/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/timezone_provider-0.0.16/src/./data/iana_normalizer.rs.data:6:6
   |
6  |     ($providername:ident) => {
   |      ^^^^^^^^^^^^^^^^^^^

error[E0432]: unresolved import `timezone_provider::prelude`
  --> /Users/rlin/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/temporal_rs-0.0.11/src/tzdb.rs:42:24
   |
42 | use timezone_provider::prelude::*;
   |                        ^^^^^^^ could not find `prelude` in `timezone_provider`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `temporal_rs` (lib) due to 2 previous errors
```

Would you please take a look?

**Comment by bartlomieju** [comment]
See https://github.com/denoland/deno_core/pull/1191 for solution - you need to pass `-Csymbol-mangling-version=v0` compiler flag.

**Comment by linrongbin16** [comment]
Thank you!
